/*
	[%
		TOKENS = {
			home_breadcrumb = "Ana Sayfa"
			your_payment_breadcrumb = "Your Payment"
			error = "Hata:"
			error_title = "Göndərdiyivizlə əlagəli bir problem əmələ gəlmişdir."
			PAYPAL_UNABLE_TO_CONNECT = "Unable to connect to PayPal."
			PAYPAL_TRY_LATER = "Please try again later."
			PAYPAL_ERROR_PROCESSING = "Unable to verify payment."
			PAYPAL_CONTACT_LIBRARY = "Əlagə İnformasiyası"
			PAYPAL_ERROR_STARTING = "Unable to start your payment."
			return = "Bu materyali Qaytar "
		}
	%]
*/