/*
	[%
		TOKENS = {
			home_breadcrumb = "Koha"
			your_payment_breadcrumb = "Your Payment"
			error = "Chyba"
			error_title = "došlo k chybě při zpracování vaší platby"
			PAYPAL_UNABLE_TO_CONNECT = "Nepodařilo se připojit ke službě PayPal."
			PAYPAL_TRY_LATER = "Zkuste to prosím později"
			PAYPAL_ERROR_PROCESSING = "Nebylo možné ověřit platbu."
			PAYPAL_CONTACT_LIBRARY = "Pro ověření platby prosím kontaktujte knihovníka."
			PAYPAL_ERROR_STARTING = "Unable to start your payment."
			return = "Zpět k podrobnostem pokuty"
		}
	%]
*/