/*
	[%
		TOKENS = {
			home_breadcrumb = "Home"
			your_payment_breadcrumb = "Your Payment"
			error = "Error"
			error_title = "there was a problem processing your payment"
			PAYPAL_UNABLE_TO_CONNECT = "Unable to connect to PayPal."
			PAYPAL_TRY_LATER = "Please try again later."
			PAYPAL_ERROR_PROCESSING = "Unable to verify payment."
			PAYPAL_CONTACT_LIBRARY = "संपर्क माहिती"
			PAYPAL_ERROR_STARTING = "Unable to start your payment."
			return = "{0} -- स्वयंसेवा वस्तु घेणे "
		}
	%]
*/