/*
	[%
		TOKENS = {
			home_breadcrumb = "Uma"
			your_payment_breadcrumb = "Your Payment"
			error = "Sala"
			error_title = "iha problema ho ita nia pagamentu"
			PAYPAL_UNABLE_TO_CONNECT = "La konsege atu liga ba PayPal."
			PAYPAL_TRY_LATER = "Please try again later."
			PAYPAL_ERROR_PROCESSING = "La konsege atu verifika pagamentu."
			PAYPAL_CONTACT_LIBRARY = "Faz favor kontaktu biblioteka ne'e atu verifika pagamentu."
			PAYPAL_ERROR_STARTING = "Unable to start your payment."
			return = "Fila ba multa detalle"
		}
	%]
*/